# Generated by Django 6.0.3 on 2026-03-31 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicnote',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='academicnote',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contentanalysis',
            name='complexity_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contentanalysis',
            name='readability_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='contentanalysis',
            name='sentence_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentanalysis',
            name='suggestions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contentanalysis',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importantquestion',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='importantquestion',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notesummary',
            name='bullet_points',
            field=models.TextField(blank=True, help_text='Bullet point summary'),
        ),
        migrations.AddField(
            model_name='notesummary',
            name='one_line_summary',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.ManyToManyField(blank=True, related_name='study_plans', to='core.academicnote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted', models.BooleanField(default=False)),
                ('correct', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.importantquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
