# Generated by Django 5.2.4 on 2026-04-06 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DSATopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='academicnote',
            name='note_type',
            field=models.CharField(choices=[('lecture', 'Lecture Notes'), ('pyq', 'Previous Year Questions'), ('assignment', 'Assignment'), ('reference', 'Reference Material')], default='lecture', max_length=50),
        ),
        migrations.AddField(
            model_name='academicnote',
            name='semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserDSATopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('quiz_score', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dsatopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsa_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
