# Generated by Django 5.2.4 on 2026-04-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dsatopic_academicnote_note_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesummary',
            name='bullet_points',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notesummary',
            name='key_points',
            field=models.TextField(),
        ),
    ]
